microserviceConfig:
   microservice-FMIS:
    JZFMISSVR:
      context: EnterpriseServer
      objectName:
        SecurityObject:
          method: Login
   
#  BZServer:
#  ZJServer:
#  JYPTServer:




