microserviceConfig:
   microservice-FMIS:
    JZFMISSVR:
      context: EnterpriseServer
      objectName:
        SecurityObject:
          method: Login
   microservice-BZPT:
      BZServer:
      context: EnterpriseServer
      objectName:
         
#  BZServer:
:
#  ZJServer:
#  JYPTServer:




