server:
  port: 8097
spring:
  application:
    name: config-client-refresh
management:
  security:
    enabled: false
eureka:
  client:
    health-check:
      enabled: true
    service-url:
      defaultZone: http://localhost:8071/eureka/
profile: 3222
